# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "13e964322d91bc5bd22a4234d2bc5870"
name = "promo-banner"
handle = "promo-banner-7"
application_url = "https://shopify-mu-seven.vercel.app"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://pregnant-attempted-mazda-binary.trycloudflare.com/auth/callback",
  "https://pregnant-attempted-mazda-binary.trycloudflare.com/auth/shopify/callback",
  "https://pregnant-attempted-mazda-binary.trycloudflare.com/api/auth/callback",
  "https://shopify-mu-seven.vercel.app/auth/callback",
  "https://shopify-mu-seven.vercel.app/api/auth/callback"
]

[pos]
embedded = false
